export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';

export const PRODUCT_SAVE_REQUEST = 'PRODUCT_SAVE_REQUEST';
export const PRODUCT_SAVE_SUCCESS = 'PRODUCT_SAVE_SUCCESS';
export const PRODUCT_SAVE_FAIL = 'PRODUCT_SAVE_FAIL';

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL';

export const PRODUCT_REVIEW_SAVE_REQUEST = 'PRODUCT_REVIEW_SAVE_REQUEST';
export const PRODUCT_REVIEW_SAVE_SUCCESS = 'PRODUCT_REVIEW_SAVE_SUCCESS';
export const PRODUCT_REVIEW_SAVE_FAIL = 'PRODUCT_REVIEW_SAVE_FAIL';
export const PRODUCT_REVIEW_SAVE_RESET = 'PRODUCT_REVIEW_SAVE_RESET';

export const TOP_PRODUCT_LIST_REQUEST = 'TOP_PRODUCT_LIST_REQUEST';
export const TOP_PRODUCT_LIST_SUCCESS = 'TOP_PRODUCT_LIST_SUCCESS';
export const TOP_PRODUCT_LIST_FAIL = 'TOP_PRODUCT_LIST_FAIL';

export const DISCOUNT_PRODUCT_LIST_REQUEST = 'DISCOUNT_PRODUCT_LIST_REQUEST';
export const DISCOUNT_PRODUCT_LIST_SUCCESS = 'DISCOUNT_PRODUCT_LIST_SUCCESS';
export const DISCOUNT_PRODUCT_LIST_FAIL = 'DISCOUNT_PRODUCT_LIST_FAIL';

export const FIND_TOP_LESS_PRICES_REQUEST = 'FIND_TOP_LESS_PRICES_REQUEST';
export const FIND_TOP_LESS_PRICES_SUCCESS = 'FIND_TOP_LESS_PRICES_SUCCESS';
export const FIND_TOP_LESS_PRICES_FAIL = 'FIND_TOP_LESS_PRICES_FAIL';

